# Generated by Django 4.2 on 2023-11-01 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_historicalprofile'),
        ('social', '0004_alter_post_title'),
    ]

    operations = [
    ]
