# Generated by Django 4.2 on 2023-11-01 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_merge_0003_historicalprofile_0004_alter_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
