# Generated by Django 4.2.4 on 2023-11-09 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_category_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
    ]
