# Generated by Django 4.2.4 on 2023-11-10 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalprofile',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Perfil', 'verbose_name_plural': 'historical Perfiles'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Posteo', 'verbose_name_plural': 'Posteos'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfiles'},
        ),
    ]
